#test11-1.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: http
  strategy:
    type: RollingUpdate #recreate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 3
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: httpd-con
        image: httpd:alpine3.20
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

