#goapp-with-schedule.yaml

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    
    name: myapp
spec:
  nodeSelector:
    memsize: "high" 
    #스케줄링 조건을 걸어 두면 
    #memsize=high 라는 해당 라벨이 없을 경우 실행이 안된다 
  containers:
  - name: myapp
    image: dangtong/goapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
